### ISSUE TITLE
Migrate away from Enzyme tests in favor of React Testing Library

### ISSUE THREAD

**Issue by adamstankiewicz** [openedx/wg-frontend#166] opened 2023-05-24 11:20 UTC
We recently noticed during our attempt to ensure Paragon is compatible with React 18 that using [Enzyme](https://enzymejs.github.io/enzyme/) with this React version for JavaScript tests will not be compatible, as Enzyme is largely no longer maintained. See https://dev.to/wojtekmaj/enzyme-is-dead-now-what-ekl for additional context, but the short of it is:

* Enzyme is no longer actively maintained.
* It does not support React hooks.
* There is no and will be no support for React 18.

The recommended alternative to Enzyme is [React Testing Library](https://testing-library.com/docs/react-testing-library/intro/). Migrating between these test frameworks will not be as trivial as drop-in replacements; the mindsets in using Enzyme vs. React Testing Library are different: with Enzyme, you can (and sometimes have to) rely on implementation details of what you're testing whereas with React Testing Library, you're encouraged more to think about testing from a user's perspective (e.g., is there an element with this matching {text | a11y `role` | `data-testid` | etc) rendered. From there, you can access the underlying DOM node to make further assertions about class names, etc. if needed.

Related, there is a proposal to officially deprecate Enzyme through Open edX and amend the [OEP-11](https://open-edx-proposals.readthedocs.io/en/latest/best-practices/oep-0011-bp-FED-technology.html) that recommends the use of Enzyme to suggest the use of React Testing Library instead: https://github.com/openedx/open-edx-proposals/pull/487

**Comment by adamstankiewicz** [comment] 2023-05-24 23:46
> I checked frontend-template-application, and for better or worse there's no enzyme in there.  (Maybe because there are no real tests. :P)  So, for now, the only urgent thing to do is change OEP-11.

Yep, that sounds about right 😃

**Comment by arbrandes** [comment] 2024-03-06 18:09
Closing as duplicate of https://github.com/openedx/public-engineering/issues/195.

**Closed by arbrandes** 2024-03-06 18:09 UTC
Labels: epic, maintenance
